# Generated by Django 5.2.13 on 2026-06-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
