# Generated by Django 5.2.13 on 2026-06-25 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_admin_registro', models.CharField(blank=True, max_length=100)),
                ('protocolo', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo_animal', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('ave', 'Ave'), ('coelho', 'Coelho'), ('cavalo', 'Cavalo'), ('bovino', 'Bovino'), ('suino', 'Suíno'), ('caprino', 'Caprino'), ('reptil', 'Réptil'), ('anfibio', 'Anfíbio'), ('silvestre', 'Silvestre'), ('marinho', 'Marinho')], max_length=20)),
                ('tipo_risco', models.CharField(choices=[('maus_tratos', 'Maus-tratos'), ('abandono', 'Abandono'), ('ferido', 'Ferido'), ('doente', 'Doente'), ('desnutrido', 'Desnutrido'), ('em_perigo', 'Em perigo'), ('atropelado', 'Atropelado'), ('preso', 'Preso'), ('envenenamento', 'Envenenamento'), ('exploracao', 'Exploração'), ('violencia', 'Violência')], max_length=20)),
                ('descricao', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ocorrencias.denuncia')),
            ],
        ),
    ]
