# Generated by Django 5.2.13 on 2026-04-22 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_admin_registro', models.CharField(blank=True, max_length=100)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_animal', models.CharField(choices=[('cachorro', 'Cachorro (ex: vira-lata, poodle)'), ('gato', 'Gato (ex: doméstico)'), ('ave', 'Ave (ex: papagaio, galinha)'), ('coelho', 'Coelho'), ('cavalo', 'Cavalo'), ('bovino', 'Bovino (ex: boi, vaca)'), ('suino', 'Suíno (ex: porco)'), ('caprino', 'Caprino (ex: cabra, bode)'), ('reptil', 'Réptil (ex: cobra, lagarto)'), ('anfibio', 'Anfíbio (ex: sapo, cobra)'), ('silvestre', 'Animal silvestre (ex: macaco, raposa)'), ('marinho', 'Animal marinho (ex: peixe, tartaruga)')], max_length=20)),
                ('tipo_risco', models.CharField(choices=[('maus_tratos', 'Maus-tratos'), ('abandono', 'Abandono'), ('ferido', 'Animal ferido'), ('doente', 'Doente'), ('desnutrido', 'Desnutrido'), ('em_perigo', 'Em perigo'), ('atropelado', 'Atropelado'), ('preso', 'Preso/Aprisionado'), ('envenenamento', 'Suspeita de envenenamento'), ('exploracao', 'Exploração ilegal'), ('violencia', 'Violência física')], max_length=20)),
                ('descricao', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
