# Generated by Django 5.2.13 on 2026-06-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
