# Generated by Django 5.2.13 on 2026-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orgao',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_animal',
            field=models.CharField(choices=[('cachorro', 'Cachorro (ex: vira-lata, poodle)'), ('gato', 'Gato (ex: doméstico)'), ('ave', 'Ave (ex: papagaio, galinha)'), ('coelho', 'Coelho'), ('cavalo', 'Cavalo'), ('bovino', 'Bovino (ex: boi, vaca)'), ('suino', 'Suíno (ex: porco)'), ('caprino', 'Caprino (ex: cabra, bode)'), ('reptil', 'Réptil (ex: cobra, lagarto)'), ('anfibio', 'Anfíbio (ex: sapo)'), ('silvestre', 'Animal silvestre (ex: macaco, raposa)'), ('marinho', 'Animal marinho (ex: peixe, tartaruga)')], max_length=20),
        ),
    ]
