# Generated by Django 5.2.14 on 2026-05-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_delete_orgao_alter_denuncia_tipo_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='email_contato',
            field=models.EmailField(blank=True, help_text='Email do denunciante para receber o protocolo', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Telefone/Celular do denunciante para receber o protocolo', max_length=20, null=True),
        ),
    ]
