# Generated by Django 5.2.13 on 2026-06-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_remove_evidencia_url_imagem_evidencia_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
