# Generated by Django 5.2.14 on 2026-05-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_denuncia_email_contato_denuncia_telefone_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='protocolo',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_animal',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('ave', 'Ave'), ('coelho', 'Coelho'), ('cavalo', 'Cavalo'), ('bovino', 'Bovino'), ('suino', 'Suíno'), ('caprino', 'Caprino'), ('reptil', 'Réptil'), ('anfibio', 'Anfíbio'), ('silvestre', 'Silvestre'), ('marinho', 'Marinho')], max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_risco',
            field=models.CharField(choices=[('maus_tratos', 'Maus-tratos'), ('abandono', 'Abandono'), ('ferido', 'Ferido'), ('doente', 'Doente'), ('desnutrido', 'Desnutrido'), ('em_perigo', 'Em perigo'), ('atropelado', 'Atropelado'), ('preso', 'Preso'), ('envenenamento', 'Envenenamento'), ('exploracao', 'Exploração'), ('violencia', 'Violência')], max_length=20),
        ),
    ]
