# Generated by Django 5.2.13 on 2026-06-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_alter_denuncia_latitude_alter_denuncia_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
