# Generated by Django 5.2.14 on 2026-05-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_denuncia_email_contato_denuncia_telefone_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='telefone_contato',
        ),
    ]
